### ISSUE TITLE
App does not auto update

### ISSUE THREAD

**Issue by Zeusmist** [Cap-go/capacitor-updater#142]
Hi there.
I followed all the instructions given here [](https://capgo.app/blog/update-your-capacitor-apps-seamlessly-using-capacitor-updater/)
but my app does not auto-update when I open the app a second time after the update is supposed to have auto-install.

- I build the app (web and android) and uploaded it to Capgo with version 1.0.5
- I installed the android build in my emulator and open to see it is working.
- Then I updated the version in package.json to 1.0.6 and then rebuild the app (web build)
- I upload the new build to Capgo
- I open my android app for auto-update.
- I close the app and re-open it, but no update shows.

Here is my configuration:
```
"dependencies": {
    "@capgo/capacitor-updater": "^4.14.17",
}
```

**src/index.js**
```
import { CapacitorUpdater } from "@capgo/capacitor-updater";
CapacitorUpdater.notifyAppReady();
```

**capacitor.config.ts**
```
plugins: {
    CapacitorUpdater: {
      autoUpdate: true,
    },
 },
```

Your help is much appreciated. Thank you.

**Comment by riderx** [comment]
Hello do you use Capgo backend ?
can you share the log of xcode or android studio ?

**Comment by Zeusmist** [comment]
Hi @riderx Thank you for responding quickly.

No, I don't use Capgo backend.

Neither did I get any logs on Android studio.
Even when I ran `npx cap run android`. 
That command simply built the app and installed it on my emulator.

**Comment by riderx** [comment]
There should be log in logcat: https://developer.android.com/studio/debug/am-logcat
if you don't see any log it mean it's not installed

**Comment by Zeusmist** [comment]
@riderx These are the Capacitor logs I get each time.
In one of the logs, I can see that NotifyAppReady was interrupted

> ee.forgr.capacitor_updater.CapacitorUpdaterPlugin$DeferredNotifyAppReadyCheck was interrupted.

[https://gist.github.com/Zeusmist/1f7bded339f2256706a7e843829ae6ae](https://gist.github.com/Zeusmist/1f7bded339f2256706a7e843829ae6ae)

**Comment by riderx** [comment]
Hey I think I found your issue I implemented timeout in v 4.15, I didn't see in android the value was millisecond and iOS it was second.
Last version [4.15.5](https://github.com/Cap-go/capacitor-updater/tree/4.15.5) should fix this.

**Comment by Zeusmist** [comment]
@riderx The issue is not yet resolved.
It still behaves the same.

Here is the result from using this new version.

- Build and upload app

- [Logs from first app open after install](https://gist.github.com/Zeusmist/5ba94dd3bc782475e7933472d0340cf9)

- Build updated app and upload.

- [Logs from second open, this is supposed to fetch the updates from server](https://gist.github.com/Zeusmist/9dd9d7a0530b2851324f5124854e66c8)

- [Logs from third open, the app is supposed to have the updates visible](https://gist.github.com/Zeusmist/d2891166fbf3af5b121b4fbf5369dff8)

I noticed the following things:
- All logs seem to be the same.
- The logs have an error `ee.forgr.capacitor_updater.CapacitorUpdaterPlugin$DeferredNotifyAppReadyCheck was interrupted.`
- Sometimes upload does not have a package in Capgo dashboard, see screenshot below. 
![image](https://user-images.githubusercontent.com/51177741/211000398-2b99fd69-2387-45e0-a89b-e73af7be138d.png)

**Comment by riderx** [comment]
`DeferredNotifyAppReadyCheck` is a normal message, nothing to worry.
i don't find `games.mita.app` in capgo database, can you send me your email in discord dm to check your account ?

**Comment by riderx** [comment]
ok found your account

**Comment by riderx** [comment]
If you have 0 device, it means you probably don't have the plugin installed in the app, did you npx cap sync ?

**Comment by Zeusmist** [comment]
@riderx Yes, I ran npx cap sync.

**Comment by riderx** [comment]
what do you see in device logs ?

**Comment by Zeusmist** [comment]
I do not have any devices in the devices list.

**Comment by riderx** [comment]
Device log in android studio

**Comment by Zeusmist** [comment]
The logs I get are the ones I commented above here: https://github.com/Cap-go/capacitor-updater/issues/142#issuecomment-1373477660

**Comment by riderx** [comment]
In your logs, you have the message `message Cannot get channel` you don't have made your channel public so the app don't get the update

**Comment by riderx** [comment]
Ok it was linked to https://github.com/Cap-go/capacitor-updater/issues/141 it should be good now, please set your channel to public !

**Comment by Zeusmist** [comment]
@riderx How do I set channel to public

**Comment by riderx** [comment]
`npx @capgo/cli@latest set -channel=production -s default`

**Comment by Zeusmist** [comment]
@riderx Thank you. The auto-update works now after setting channel as default.
