### ISSUE TITLE
problem: "no new version available" behaves differently between IOS and android

### ISSUE THREAD

**Issue by WcaleNieWolny** [Cap-go/capacitor-updater#428]
![image](https://github.com/user-attachments/assets/74a2e9c8-4f48-417a-a2fb-e2290eedac2a)
![image](https://github.com/user-attachments/assets/a42b1d79-0fb5-4050-b6a6-39cba7e8363d)

**Comment by riderx** [comment]
Fixed

**Comment by WcaleNieWolny** [comment]
No, not fixed. I expected the opposite to be done (Android to have `error` to false).
https://github.com/Cap-go/capacitor-updater/commit/a2563c0a2a0526cc14201d2a29fdae1c9031fe05

Take a look at the following log:
```
✨  Capacitor-updater: endBackGroundTaskWithNotif No new version available
✨  Capacitor-updater: semaphoreWait 10000
✨  Capacitor-updater: Stats sent for download_fail, version 1.0.95
```
It makes ZERO sense `No new version available` is the desired behavior and it is not an error

**Comment by riderx** [comment]
This is the documented bahavior
